In [2]:
import numpy as np
import pandas as pd

# A. Pandas fundamental data structure 
### 1. Series Object
### 2. DataFrame Object
### 3. Index Object

### 1. The pandas 'series' object

In [127]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [128]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [129]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [130]:
data[1]

0.5

In [131]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [132]:
## series as a generalized numpy array
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [133]:
data['b']

0.5

In [134]:
## non-contiguous or non-sequential indices:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data
data[5]

0.5

In [135]:
##series as a specialized dictionary
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [136]:
population['California']

38332521

In [137]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [138]:
##summary: constructing series objects
#>>>pd.Series(data, index=index)
# where index is an optional argument and data can be one of many entities
# data can be a numpy array, in which case index defaults to an integer sequence
# eg.
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [139]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [140]:
# data can be a dictionary
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [141]:
# index can be explicitly set
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

### 2. The Pandas DataFrame object

In [151]:
# If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names
# Think of a DataFrame as a sequence of aligned Series objects. 
# Here, by "aligned" we mean that they share the same index.

## DataFrame as a generalized numpy array
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [152]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [153]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [154]:
states.columns

Index(['population', 'area'], dtype='object')

In [155]:
## DataFrame as a specialized dictionary
# Similarly, we can also think of a DataFrame as a specialization of a dictionary. Where a dictionary maps a key to a value, a DataFrame maps a column name to a Series of column data.
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [156]:
## Constructing DataFrame objects
pd.DataFrame(population, columns=['population']) #constructed from a single series object

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [148]:
# from a list of dicts
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [147]:
#if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e., "not a number") values
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [146]:
### from a dictionary of series objects
pd.DataFrame({'population': population,
              'area': area})

population       area
Alaska             NaN  1723337.0
California  38332521.0   423967.0
Florida     19552860.0        NaN
Illinois    12882135.0        NaN
New York    19651127.0        NaN
Texas       26448193.0   695662.0

In [145]:
### from a 2-D numpy array
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.576912  0.299405
b  0.002100  0.910011
c  0.667280  0.393209

In [144]:
### from a numpy structured array
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [143]:
pd.DataFrame(A)

0  1  2  3
0  3  6  7  2
1  0  3  1  7
2  3  1  5  5

### 3. The Pandas Index Object

In [157]:
"""We have seen here that both the Series and DataFrame objects contain an explicit index 
that lets you reference and modify data. This Index object is an interesting structure in 
itself, and it can be thought of either as an immutable array or as an ordered set 
(technically a multi-set, as Index objects may contain repeated values)"""

ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [158]:
## index as an immutable array
ind[1]

3

In [159]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [160]:
print(ind.size, ind.shape, ind.ndim, ind.dtype) # attributes of intex object

5 (5,) 1 int64


In [167]:
#One difference between Index objects and NumPy arrays is that indices are immutable
ind[1] = 0

TypeError: Index does not support mutable operations

In [163]:
## Index as ordered set
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [164]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [165]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [166]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

# B. Data Indexing and Selection

In [3]:
#Data selection in series
## Series as dictionary
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [4]:
data['b']

0.5

In [6]:
'a' in data

True

In [7]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [11]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

## Series as 1D array

In [14]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [17]:
# slicing by implicit 'integer' index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [18]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [19]:
# fancy indexing
data[['a','e']]

a    0.25
e    1.25
dtype: float64

# Indexers: loc, iloc, ix

In [21]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [22]:
# explicit index when indexing
data[1]

'a'

In [23]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [25]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [26]:
data.loc[1:3]

1    a
3    b
dtype: object

In [27]:
data.iloc[1]

'b'

In [28]:
data.iloc[1:3]

3    b
5    c
dtype: object

# Data selection in DataFrame
## DataFrame as a dictionary

In [32]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [34]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [35]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [36]:
data.area is data['area']

True

In [37]:
data.pop is data['pop']

False

In [38]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## DataFrame as 2D array

In [66]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.00000000e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [44]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [45]:
data.T #Transpose

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [46]:
#Accessing a row
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [47]:
#Accessing a column
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [49]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [50]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [52]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [53]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## Additional indexing convention

In [63]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [64]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [65]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# C. Operating on Data in Pandas

In [69]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [71]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [72]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [73]:
np.sin(df * np.pi / 4)

A         B         C         D
0  7.071068e-01 -0.707107 -0.707107  0.707107
1  1.224647e-16  0.000000  0.707107 -0.707107
2 -2.449294e-16  0.000000  0.707107  1.000000

# UFuncs: Index Alignment

## Index alignment in Series

In [76]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [77]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [78]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [79]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [80]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [82]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A  B
0  18  6
1   8  6

In [83]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  1  3  8
1  1  9  8
2  9  4  1

In [84]:
A + B

A    B   C
0  21.0  7.0 NaN
1  17.0  7.0 NaN
2   NaN  NaN NaN

In [86]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  21.0   7.0  17.5
1  17.0   7.0  17.5
2  13.5  18.5  10.5

## Ufuncs: Operations Between DataFrame and Series

In [87]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 6, 7, 2],
       [0, 3, 1, 7],
       [3, 1, 5, 5]])

In [88]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-3, -3, -6,  5],
       [ 0, -5, -2,  3]])

In [89]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -3 -3 -6  5
2  0 -5 -2  3

In [90]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -3  0  1 -4
1 -3  0 -2  4
2  2  0  4  4

In [91]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    7
Name: 0, dtype: int64

In [92]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -3.0 NaN -6.0 NaN
2  0.0 NaN -2.0 NaN

# D. Handling Missing Data

### Trade-Offs in Missing Data Conventions

## Missing Data in Pandas

### None: Pythonic missing data

In [94]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [95]:
# To see the time of execution of 'dtype=none' and 'dtype=int' 
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
84.1 ms ± 814 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
2.57 ms ± 51.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [98]:
# Addition between an integer and None is undefined.
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### NaN: Missing numerical data

In [99]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [100]:
1 + np.nan

nan

In [101]:
0 *  np.nan

nan

In [102]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [103]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

### NaN and None in Pandas

In [104]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [105]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [106]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

### Operating on Null Values

### Detecting null values: isnull(), notnull()

In [110]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

#### Boolean masks can be used directly as a Series or DataFrame index:

In [112]:
data[data.notnull()]

0        1
2    hello
dtype: object

### Dropping null values
#### dropna(), fillna()

In [113]:
data.dropna()

0        1
2    hello
dtype: object

In [114]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [115]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [116]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [117]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [118]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [119]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

### Filling Null values

In [120]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [122]:
data.fillna(0) # filling with 0

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [123]:
# forward-fill
data.fillna(method='ffill') # filling with previous value

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [124]:
# back-fill
data.fillna(method='bfill') # filling with next values

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [125]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [126]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# E. Hierarchical Indexing

# F. Combining Datasets: Concat and Append

# G. Combining Datasets: Merge and Join

# H. Aggregation and Grouping

# I. Pivot Tables

# J. Vectorized String Operations

# K. Working with Time Series

# L. High-Performance Pandas: eval() and query()

# M. Further Resources