# # Linear Algebra

In [4]:
import numpy as np
from scipy import linalg, sparse

In [20]:
#A = np.matrix(np.random.random((2,2)))
#B = np.asmatrix(b)
#C = np.mat(np.random.random((10,5)))
A = np.mat([[3,4], [5,6]])
print(A)

[[3 4]
 [5 6]]


In [22]:
# Determinant
linalg.det(A)

-2.0

In [25]:
# Inverse
A.I
#linalg.inv(A)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [17]:
# Trace
np.trace(A)

9

In [21]:
# Rank
np.linalg.matrix_rank(A)

2

In [30]:
# Eigenvalues and Eigenvectors
la,v=linalg.eig(A)
print(la)
print(A)

[-0.21699057+0.j  9.21699057+0.j]
[[3 4]
 [5 6]]
